preload = ~/Pictures/wallpapers/1332076.jpeg
preload = ~/Pictures/wallpapers/artsy.jpg
preload = ~/Pictures/wallpapers/socratesv2.jpg
wallpaper = ,~/Pictures/wallpapers/socratesv2.jpg
 
# wallpaper = , ~/Downloads/1354305.jpeg
#fully disable ipc
ipc = off

